### ISSUE TITLE
Hue white

### ISSUE THREAD

**Issue by lurendrejer** [rogro82/com.hue.zigbee#1]
Hi, could the hue whites be added relatively easy - if i gave you the ID's? 
I wouldn't care about wrong icons, etc. :)

**Comment by rogro82** [comment]
Sure just post the IDs ( productId and deviceId ) and the light capabilities ( i guess they are just onoff and dim for those ) and I will add them

**Comment by lurendrejer** [comment]
Hi.

PID=LWB006 / DID=256

And yes, the just dim/on/off :)

Thank you in advance.

Den 18. okt. 2017 5.16 PM skrev rogro82 <notifications@github.com>:

Sure just post the IDs ( productId and deviceId ) and the light capabilities ( i guess they are just onoff and dim for those ) and I will add them

**Comment by rogro82** [comment]
I have added the white lamps (LWB006). Can you confirm if they are working correctly so i can update the readme.

**Comment by lurendrejer** [comment]
Will do, as Soon ad i get home from Work.

Den 20. okt. 2017 1.53 AM skrev rogro82 <notifications@github.com>:

I have added the white lamps (LWB006). Can you confirm if they are working correctly so i can update the readme.

**Comment by lurendrejer** [comment]
It Works. Thank you :)

Den 20. okt. 2017 1.53 AM skrev rogro82 <notifications@github.com>:

I have added the white lamps (LWB006). Can you confirm if they are working correctly so i can update the readme.

**Comment by rogro82** [comment]
Thanks for reporting.
